name: check_ubuntu

on: [push, pull_request]

jobs:
  centos_8:
    # We want to run on external PRs, but not on our own internal PRs
    # as they'll be run by the push to the branch.
    if: ( github.event_name == 'push' ||
        github.event.pull_request.head.repo.full_name != github.repository ) &&
        ! endsWith(github.ref, '-notest')

    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false

    steps:
      - name: packaging
        run: |
            sudo cat /etc/os-release
            sudo apt-get -y update
            sudo apt-get install -y procmail createrepo awscli reprepro
      - name: call action to send Telegram message on failure
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_CORE_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_CORE_TO }}
        uses: ./.github/actions/send-telegram-notify
        if: failure()
