name: linux

on: [push]

jobs:
  ubuntu-1804:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false

    steps:
      - name: packaging
        run: |
            sudo cat /etc/os-release
            sudo cat /proc/cpuinfo
            sudo free
            sudo df -lh
            sudo lsblk
      - name: call action to send Telegram message on failure
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_CORE_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_CORE_TO }}
        uses: ./.github/actions/send-telegram-notify
        if: failure()
